# Pull the image (and version) 
FROM node:16.13.1

# Install
RUN mkdir -p /node
ADD . /node
WORKDIR /node
RUN npm install
#CMD ['node', 'server.js']

# permission
# RUN chmod 777 node_modules

# Start 
CMD ["npm", "start"]


# docker build -t frontend-img .
# docker run --name frontend-con -it -p 3000:3000 --rm frontend-img