FROM python:3.8.8


WORKDIR /backend
COPY . ./


RUN pip install --upgrade pip
RUN pip install -r requirement.txt 


EXPOSE 5000

CMD ["python", "app.py"]

#docker run --name backend-con -it -p 5000:5000 --rm backend-img