FROM nginx:latest

# Delete nginx default configuration file in virtual directory
# 가상 공간의 nginx 기본 설정파일 삭제 후 작성한 설정파일로 대체
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /app/nginx/conf.d

CMD ["nginx", "-g", "daemon off;"]

EXPOSE 80

# docker build -t nginx-img .
# docker run -v nginx:/app --name nginx-con -it -p 8080:8080 --rm nginx-img

#nginx-test
#nginx-con
#2dc5e945d536932fb024437dea4e3039ebc3966e598884b9135c3eb88a47a488
#docker start nginx-con

#docker build --tag nginx-img .

#/var/lib/docker/volumes/nginx/_data
#/var/lib/docker/volumes/nginx/_data
#docker run -v nginx:/app --name nginx-con -it -p 8080:8080 --rm nginx-img