FROM nginx:latest

COPY config/nginx.conf /etc/nginx/conf.d/nginx.conf

CMD ["nginx", "-g", "daemon off;"]

EXPOSE 80

# docker build -t nginx .
# docker run --name nginx-con -it -p 8080:80 --rm nginx